//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTPlanningTasksWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JobLog
    {
        public int Id { get; set; }
        public string JobName { get; set; }
        public string JobGroup { get; set; }
        public Nullable<System.DateTime> PreviousTime { get; set; }
        public Nullable<System.DateTime> CurrentTime { get; set; }
        public Nullable<System.DateTime> NextTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Times { get; set; }
        public string Exception { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
